title: hc0208.github.io
url: https://hc0208.github.io/
description: Hiroki Chidaが気分で更新するブログです。日々感じていることをメモがわりに書いていきます。

sass:
  sass_dir: assets/css

paginate: 10

permalink: /blog/:year/:month/:day

markdown: kramdown
gems:
  - jekyll-sitemap
  - github-pages
exclude:
  - Gemfile
  - Gemfile.lock
